import Link from "next/link";
import Head from "next/head";

type LayoutProps = {
    children: React.ReactNode | React.ReactNode[];
};

export const Layout = ({ children }: LayoutProps) => {
    return (
        <>
            <Head>
                <title>Amcef ToDo List</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/amcef_fav.webp" />
            </Head>
            <div className="p-3 xl:w-screen xl:h-screen flex flex-col justify-between overflow-hidden">
                <div>
                    <Link href="/" className=" uppercase font-bold text-xl">
                        Home
                    </Link>
                </div>
                {children}
                <div className="flex justify-end items-end mt-3">
                    <span className="mr-2">Created by:</span>
                    <span className="font-bold"> Marek Matušica </span>
                </div>
            </div>
        </>
    );
};
